<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SubUnitSeeder extends Seeder
{
    public function run()
    {
        DB::table('subunits')->insert([
            ['KODE_SUB_UNITS' => 1, 'NAMA_SUB_UNITS' => ' SEKRATARIAT DAERAH', 'KODE_BIDANG' => 1, 'KODE_UNITS' => 1],
            ['KODE_SUB_UNITS' => 2, 'NAMA_SUB_UNITS' => 'Walikota', 'KODE_BIDANG' => 1, 'KODE_UNITS' => 1],
            ['KODE_SUB_UNITS' => 3, 'NAMA_SUB_UNITS' => 'Wakil Walikota', 'KODE_BIDANG' => 1, 'KODE_UNITS' => 1],
            ['KODE_SUB_UNITS' => 4, 'NAMA_SUB_UNITS' => 'Sekretariat Daerah', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 2],
            ['KODE_SUB_UNITS' => 5, 'NAMA_SUB_UNITS' => 'SEKRETARIAT KPU KOTA PALEMBANG', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 2],
            ['KODE_SUB_UNITS' => 6, 'NAMA_SUB_UNITS' => 'KANTOR PELAYANAN PERIJINAN TERPADU', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 2],
            ['KODE_SUB_UNITS' => 7, 'NAMA_SUB_UNITS' => 'KECAMATAN KEMUNING', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 3],
            ['KODE_SUB_UNITS' => 8, 'NAMA_SUB_UNITS' => 'KECAMATAN BUKIT KECIL', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 4],
            ['KODE_SUB_UNITS' => 9, 'NAMA_SUB_UNITS' => 'KECAMATAN GANDUS', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 5],
            ['KODE_SUB_UNITS' => 10, 'NAMA_SUB_UNITS' => 'KECAMATAN KERTAPATI', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 6],
            ['KODE_SUB_UNITS' => 11, 'NAMA_SUB_UNITS' => 'KECAMATAN PLAJU', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 7],
            ['KODE_SUB_UNITS' => 12, 'NAMA_SUB_UNITS' => 'KECAMATAN ILIR TIMUR I', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 8],
            ['KODE_SUB_UNITS' => 13, 'NAMA_SUB_UNITS' => 'KECAMATAN ILIR TIMUR II', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 9],
            ['KODE_SUB_UNITS' => 14, 'NAMA_SUB_UNITS' => 'KECAMATAN ILIR BARAT I', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 10],
            ['KODE_SUB_UNITS' => 15, 'NAMA_SUB_UNITS' => 'KECAMATAN ILIR BARAT II', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 11],
            ['KODE_SUB_UNITS' => 16, 'NAMA_SUB_UNITS' => 'KECAMATAN SEBERANG ULU I', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 12],
            ['KODE_SUB_UNITS' => 17, 'NAMA_SUB_UNITS' => 'KECAMATAN SEBARANG ULU II', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 13],
            ['KODE_SUB_UNITS' => 18, 'NAMA_SUB_UNITS' => 'KECAMATAN SEMATANG BORANG', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 14],
            ['KODE_SUB_UNITS' => 19, 'NAMA_SUB_UNITS' => 'KECAMATAN SAKO', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 15],
            ['KODE_SUB_UNITS' => 20, 'NAMA_SUB_UNITS' => 'KECAMATAN SUKARAMI', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 16],
            ['KODE_SUB_UNITS' => 21, 'NAMA_SUB_UNITS' => 'KECAMATAN ALANG ALANG LEBAR', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 17],
            ['KODE_SUB_UNITS' => 22, 'NAMA_SUB_UNITS' => 'KECAMATAN KALIDONI', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 18],
            ['KODE_SUB_UNITS' => 23, 'NAMA_SUB_UNITS' => 'KECAMATAN JAKABARING', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 19],
            ['KODE_SUB_UNITS' => 24, 'NAMA_SUB_UNITS' => 'KECAMATAN ILIR TIMUR III', 'KODE_BIDANG' => 2, 'KODE_UNITS' => 20],
            ['KODE_SUB_UNITS' => 25, 'NAMA_SUB_UNITS' => 'Kecamatan Tanjung Sakti PUMU', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 26, 'NAMA_SUB_UNITS' => 'Kecamatan Tanjung Tebat', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 27, 'NAMA_SUB_UNITS' => 'Kecamatan Muara Payang', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 28, 'NAMA_SUB_UNITS' => 'Kecamatan Suka Merindu', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 29, 'NAMA_SUB_UNITS' => 'Dinas Pekerjaan Umum dan Penata Ruang', 'KODE_BIDANG' => 3, 'KODE_UNITS' => 21],
            ['KODE_SUB_UNITS' => 30, 'NAMA_SUB_UNITS' => 'Dinas Perumahan Rakyat dan Kawasan Pemukiman', 'KODE_BIDANG' => 3, 'KODE_UNITS' => 22],
            ['KODE_SUB_UNITS' => 31, 'NAMA_SUB_UNITS' => 'DINAS TATA KOTA PALEMBANG', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 32, 'NAMA_SUB_UNITS' => 'DINAS PENERANGAN JALAN PERTAMANAN & PEMAKAMAN KOTA PALEMBANG', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 33, 'NAMA_SUB_UNITS' => 'Dinas Perumahan Rakyat dan Kawasan Pemukiman', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 34, 'NAMA_SUB_UNITS' => 'Dinas Perhubungan Kota Palembang', 'KODE_BIDANG' => 4, 'KODE_UNITS' => 23],
            ['KODE_SUB_UNITS' => 35, 'NAMA_SUB_UNITS' => 'RSUD BARI', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 24],
            ['KODE_SUB_UNITS' => 36, 'NAMA_SUB_UNITS' => 'Dinas Kesehatan', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 37, 'NAMA_SUB_UNITS' => 'Pkm. Makrayu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 38, 'NAMA_SUB_UNITS' => 'Pkm. Gandus', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 39, 'NAMA_SUB_UNITS' => 'Pkm. 1 Ulu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 40, 'NAMA_SUB_UNITS' => 'Pkm. 4 Ulu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 41, 'NAMA_SUB_UNITS' => 'Pkm. 7 Ulu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 42, 'NAMA_SUB_UNITS' => 'Pkm. Pembina', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 43, 'NAMA_SUB_UNITS' => 'Pkm. OPI', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 44, 'NAMA_SUB_UNITS' => 'Pkm. Keramasan', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 45, 'NAMA_SUB_UNITS' => 'Pkm. Kertapati', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 46, 'NAMA_SUB_UNITS' => 'Pkm. Karya Jaya', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 47, 'NAMA_SUB_UNITS' => 'Pkm. Naga Suwidak', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 48, 'NAMA_SUB_UNITS' => 'Pkm. Taman Bacaan', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 49, 'NAMA_SUB_UNITS' => 'Pkm. Plaju', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 50, 'NAMA_SUB_UNITS' => 'Pkm. Kampus', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 51, 'NAMA_SUB_UNITS' => 'Pkm. Pakjo', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 52, 'NAMA_SUB_UNITS' => 'Pkm. Padang Selasa', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 53, 'NAMA_SUB_UNITS' => 'Pkm. Sei Baung', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 54, 'NAMA_SUB_UNITS' => 'Pkm. 23 Ilir', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 55, 'NAMA_SUB_UNITS' => 'Pkm. Merdeka', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 56, 'NAMA_SUB_UNITS' => 'Pkm. Ariodilah', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 57, 'NAMA_SUB_UNITS' => 'Pkm. Dempo', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 58, 'NAMA_SUB_UNITS' => 'Pkm. Talang Ratu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 59, 'NAMA_SUB_UNITS' => 'Pkm. Basuki Rahmat', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 60, 'NAMA_SUB_UNITS' => 'Pkm. Sekip', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 61, 'NAMA_SUB_UNITS' => 'Pkm. 5 Ilir', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 62, 'NAMA_SUB_UNITS' => 'Pkm. 11 Ilir', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 63, 'NAMA_SUB_UNITS' => 'Pkm. Boom Baru', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 64, 'NAMA_SUB_UNITS' => 'Pkm. Kenten', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 65, 'NAMA_SUB_UNITS' => 'Pkm. Sabokingking', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 66, 'NAMA_SUB_UNITS' => 'Pkm. Bukit Sangkal', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 67, 'NAMA_SUB_UNITS' => 'Pkm. Kalidoni', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 68, 'NAMA_SUB_UNITS' => 'Pkm. Sei Selincah', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 69, 'NAMA_SUB_UNITS' => 'Pkm. Multiwahana', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 70, 'NAMA_SUB_UNITS' => 'Pkm. Sematang Borang', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 71, 'NAMA_SUB_UNITS' => 'Pkm. Sosial', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 72, 'NAMA_SUB_UNITS' => 'Pkm. Sukarami', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 73, 'NAMA_SUB_UNITS' => 'Pkm. Talang Betutu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 74, 'NAMA_SUB_UNITS' => 'Pkm. Punti Kayu', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 75, 'NAMA_SUB_UNITS' => 'Pkm. Alang - Alang Lebar', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 76, 'NAMA_SUB_UNITS' => 'Pkm. Sako', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 77, 'NAMA_SUB_UNITS' => 'Pkm. Tegal Binangun', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 78, 'NAMA_SUB_UNITS' => 'RSUD Gandus', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 79, 'NAMA_SUB_UNITS' => 'Pkm. Talang Jambe', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 25],
            ['KODE_SUB_UNITS' => 80, 'NAMA_SUB_UNITS' => 'RSUD Gandus', 'KODE_BIDANG' => 5, 'KODE_UNITS' => 26],
            ['KODE_SUB_UNITS' => 81, 'NAMA_SUB_UNITS' => 'Dinas Pendidikan', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 82, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan KEMUNING', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 83, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan BUKIT KECIL', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 84, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan GANDUS', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 85, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan KERTAPATI', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 86, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan PLAJU', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 87, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan ILIR TIMUR I', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 88, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan ILIR TIMUR II', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 89, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan ILIR BARAT I', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 90, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan ILIR BARAT II', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 91, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan SEBERANG ULU I', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 92, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan SEBARANG ULU II', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 93, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan SEMATANG BORANG', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 94, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan SAKO', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 95, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan SUKARAMI', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 96, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan ALANG ALANG LEBAR', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 97, 'NAMA_SUB_UNITS' => 'UPT Dinas Pendidikan Kecamatan KALIDONI', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 27],
            ['KODE_SUB_UNITS' => 98, 'NAMA_SUB_UNITS' => 'Dinas Kebudayaan', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 28],
            ['KODE_SUB_UNITS' => 99, 'NAMA_SUB_UNITS' => 'Dinas Kepemudaan dan Olahraga', 'KODE_BIDANG' => 6, 'KODE_UNITS' => 29],
            ['KODE_SUB_UNITS' => 100, 'NAMA_SUB_UNITS' => 'DINAS SOSIAL KOTA PALEMBANG', 'KODE_BIDANG' => 7, 'KODE_UNITS' => 30],
            ['KODE_SUB_UNITS' => 101, 'NAMA_SUB_UNITS' => 'DINAS PEMADAM KEBAKARAN DAN PENANGGULANGAN BENCANA', 'KODE_BIDANG' => 7, 'KODE_UNITS' => 31],
            ['KODE_SUB_UNITS' => 102, 'NAMA_SUB_UNITS' => 'DINAS KETENAGAKERJAAN KOTA PALEMBANG', 'KODE_BIDANG' => 7, 'KODE_UNITS' => 32],
            ['KODE_SUB_UNITS' => 103, 'NAMA_SUB_UNITS' => 'DINAS PEMBERDAYAAN PEREMPUAN, PERLINDUNGAN ANAK, DAN PEMBERDAYAAN MASYARAKAT', 'KODE_BIDANG' => 8, 'KODE_UNITS' => 33],
            ['KODE_SUB_UNITS' => 104, 'NAMA_SUB_UNITS' => 'DINAS PENGENDALIAN PENDUDUK DAN KELUARGA BERENCANA', 'KODE_BIDANG' => 8, 'KODE_UNITS' => 34],
            ['KODE_SUB_UNITS' => 105, 'NAMA_SUB_UNITS' => 'DINAS KEPENDUDUKAN & PENCATATAN SIPIL KOTA PALEMBANG', 'KODE_BIDANG' => 8, 'KODE_UNITS' => 35],
            ['KODE_SUB_UNITS' => 106, 'NAMA_SUB_UNITS' => 'Dinas Pertanian dan Ketahanan Pangan', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 36],
            ['KODE_SUB_UNITS' => 107, 'NAMA_SUB_UNITS' => 'Dinas Perikanan', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 37],
            ['KODE_SUB_UNITS' => 108, 'NAMA_SUB_UNITS' => 'Badan Pelaksana Penyuluhan Pertanian, Perikanan dan Kehutanan', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 37],
            ['KODE_SUB_UNITS' => 109, 'NAMA_SUB_UNITS' => 'Dinas Peternakan dan Perikanan', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 37],
            ['KODE_SUB_UNITS' => 110, 'NAMA_SUB_UNITS' => 'Badan Ketahanan Pangan', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 37],
            ['KODE_SUB_UNITS' => 111, 'NAMA_SUB_UNITS' => 'DINAS PERTANIAN, PERIKANAN DAN KEHUTANAN KOTA PALEMBANG', 'KODE_BIDANG' => 9, 'KODE_UNITS' => 37],
            ['KODE_SUB_UNITS' => 112, 'NAMA_SUB_UNITS' => 'Dinas Koperasi dan Usaha Kecil dan Menengah', 'KODE_BIDANG' => 10, 'KODE_UNITS' => 38],
            ['KODE_SUB_UNITS' => 113, 'NAMA_SUB_UNITS' => 'Dinas Perdagangan', 'KODE_BIDANG' => 10, 'KODE_UNITS' => 39],
            ['KODE_SUB_UNITS' => 114, 'NAMA_SUB_UNITS' => 'Dinas Perindustrian', 'KODE_BIDANG' => 10, 'KODE_UNITS' => 40],
            ['KODE_SUB_UNITS' => 115, 'NAMA_SUB_UNITS' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'KODE_BIDANG' => 11, 'KODE_UNITS' => 41],
            ['KODE_SUB_UNITS' => 116, 'NAMA_SUB_UNITS' => 'Badan Pengelolaan Pajak Daerah', 'KODE_BIDANG' => 11, 'KODE_UNITS' => 42],
            ['KODE_SUB_UNITS' => 117, 'NAMA_SUB_UNITS' => 'KANTOR PELAYANAN PERIJINAN TERPADU', 'KODE_BIDANG' => 11, 'KODE_UNITS' => 42],
            ['KODE_SUB_UNITS' => 118, 'NAMA_SUB_UNITS' => 'BADAN KOORDINASI PENANAMAN MODAL DAERAH', 'KODE_BIDANG' => 11, 'KODE_UNITS' => 42],
            ['KODE_SUB_UNITS' => 119, 'NAMA_SUB_UNITS' => 'Inspektorat', 'KODE_BIDANG' => 12, 'KODE_UNITS' => 43],
            ['KODE_SUB_UNITS' => 120, 'NAMA_SUB_UNITS' => 'Badan Pengelolaan Keuangan dan Aset Daerah', 'KODE_BIDANG' => 12, 'KODE_UNITS' => 44],
            ['KODE_SUB_UNITS' => 121, 'NAMA_SUB_UNITS' => 'Badan Perencanaan Pembangunan Daerah', 'KODE_BIDANG' => 13, 'KODE_UNITS' => 45],
            ['KODE_SUB_UNITS' => 122, 'NAMA_SUB_UNITS' => 'Dinas Lingkungan Hidup dan Kebersihan', 'KODE_BIDANG' => 14, 'KODE_UNITS' => 46],
            ['KODE_SUB_UNITS' => 123, 'NAMA_SUB_UNITS' => 'Dinas Pariwisata', 'KODE_BIDANG' => 15, 'KODE_UNITS' => 47],
            ['KODE_SUB_UNITS' => 124, 'NAMA_SUB_UNITS' => 'Dinas Pariwisata', 'KODE_BIDANG' => 15, 'KODE_UNITS' => 47],
            ['KODE_SUB_UNITS' => 125, 'NAMA_SUB_UNITS' => 'BADAN KESATUAN BANGSA DAN POLITIK', 'KODE_BIDANG' => 16, 'KODE_UNITS' => 48],
            ['KODE_SUB_UNITS' => 126, 'NAMA_SUB_UNITS' => 'KESATUAN POL PP KOTA PALEMBANG', 'KODE_BIDANG' => 16, 'KODE_UNITS' => 49],
            ['KODE_SUB_UNITS' => 127, 'NAMA_SUB_UNITS' => 'SEKRETARIAT KORPRI', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
            ['KODE_SUB_UNITS' => 128, 'NAMA_SUB_UNITS' => 'Badan Kepegawaian dan Pengembangan Sumber Daya Manusia', 'KODE_BIDANG' => 17, 'KODE_UNITS' => 50],
            ['KODE_SUB_UNITS' => 129, 'NAMA_SUB_UNITS' => 'DINAS KOMUNIKASI & INFORMATIKA', 'KODE_BIDANG' => 18, 'KODE_UNITS' => 51],
            ['KODE_SUB_UNITS' => 130, 'NAMA_SUB_UNITS' => 'DINAS KEARSIPAN DAN PERPUSTAKAAN', 'KODE_BIDANG' => 18, 'KODE_UNITS' => 52],
            ['KODE_SUB_UNITS' => 131, 'NAMA_SUB_UNITS' => 'Lainnya', 'KODE_BIDANG' => 20, 'KODE_UNITS' => 53],
        ]);
    }
}
